name: Deploy Selector

on:
  pull_request:
    branches: [ main, hmg ]
    types: [closed]
  push:
    branches: [ main, hmg ]

env:
  ACTIONS_RUNNER_DEBUG: true
  ACTIONS_STEP_DEBUG: true

jobs:
  deploy:
    if: github.event_name == 'push' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    env:
      branch_name: ${{ github.ref_name }}  # Set branch_name directly

    steps:
      - name: Determine Environment
        id: set-env
        run: |
          set -euxo pipefail  # Enable debug mode and error handling
          
          if [ "$branch_name" = "main" ]; then
            echo "Setting environment to production"
            echo "deploy_env=production" >> $GITHUB_ENV
          elif [ "$branch_name" = "hmg" ]; then
            echo "Setting environment to homologation"
            echo "deploy_env=homologation" >> $GITHUB_ENV
          else
            echo "No matching environment for branch"
            exit 1
          fi
        shell: bash

      - name: Print Debug Information
        run: |
          echo "Branch Name: $branch_name"
          echo "Deployment Environment: $deploy_env"
        shell: bash

      - name: Trigger Production Workflow
        if: env.deploy_env == 'production'
        uses: ./.github/workflows/deploy-prod.yml

      - name: Trigger Homologation Workflow
        if: env.deploy_env == 'homologation'
        uses: ./.github/workflows/deploy-hmg.yml
